from __future__ import annotations

import hashlib
import json
import os
from pathlib import Path

STATIC_DIR = Path(__file__).resolve().parent / "static"
GENERATED_DIR = STATIC_DIR / "generated"

GLOBAL_CSS = (
    "css/ui-v2.css",
    "css/ui-v4.css",
    "css/ui-v6.css",
    "css/ui-v9.css",
    "css/ui-v17.css",
    "css/ui-v22.css",
    "css/ui-v23.css",
    "css/ui-v24.css",
    "css/ui-v25.css",
    "css/ui-v27.css",
    "css/ui-v28.css",
    "css/ui-v29.css",
)
LABEL_CSS = ("css/ui-v13.css",)

GLOBAL_JS = (
    "js/ui-v4.js",
    "js/ui-v6.js",
    "js/ui-v9.js",
    "js/ui-v23.js",
    "js/ui-v24.js",
    "js/ui-v25.js",
    "js/ui-v26.js",
    "js/ui-v27.js",
    "js/regression-v28.js",
    "js/ui-v29.js",
    "js/theme-controls-v32.js",
    "js/theme-preview-compat-v34.js",
    "js/terminology-v30.js",
    "js/shopping-bootstrap-v31.js",
    "js/ui-v12-bell.js",
)
LABEL_JS = (
    "js/labels-b21.js",
    "js/labels-b21-v2.js",
    "js/labels-b21-v2-patch.js",
    "js/labels-b21-v4.js",
    "js/ui-v13-fixes.js",
    "js/labels-v18.js",
    "js/labels-v22.js",
    "js/labels-v23.js",
    "js/labels-v24.js",
    "js/labels-scope-v32.js",
    "js/labels-fixes-v30.js",
)

BUNDLES = {
    "global-ui.css": GLOBAL_CSS,
    "labels-ui.css": LABEL_CSS,
    "global-ui.js": GLOBAL_JS,
    "labels-ui.js": LABEL_JS,
}


def _render_bundle(name: str, sources: tuple[str, ...]) -> tuple[str, list[dict[str, str]]]:
    chunks: list[str] = [
        "/* Generated by app.frontend_assets. Do not edit this file directly. */\n"
    ]
    manifest: list[dict[str, str]] = []
    for relative in sources:
        source = STATIC_DIR / relative
        if not source.is_file():
            raise FileNotFoundError(f"Frontend bundle source is missing: {source}")
        content = source.read_text(encoding="utf-8")
        digest = hashlib.sha256(content.encode("utf-8")).hexdigest()
        manifest.append({"path": relative, "sha256": digest})
        if name.endswith(".js"):
            chunks.append(f"\n/* ---- {relative} ---- */\n;\n{content.rstrip()}\n")
        else:
            chunks.append(f"\n/* ---- {relative} ---- */\n{content.rstrip()}\n")
    return "".join(chunks), manifest


def build_frontend_assets() -> dict[str, object]:
    """Build deterministic browser bundles from the legacy source layers.

    The individual source files remain readable while B2M migrates them into
    canonical page controllers. Production only needs the generated entrypoints,
    which prevents version-layer ordering from leaking into templates.
    """
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    result: dict[str, object] = {"bundles": {}}

    for name, sources in BUNDLES.items():
        content, source_manifest = _render_bundle(name, sources)
        target = GENERATED_DIR / name
        tmp = target.with_suffix(target.suffix + ".tmp")
        tmp.write_text(content, encoding="utf-8")
        os.replace(tmp, target)
        result["bundles"][name] = {
            "sha256": hashlib.sha256(content.encode("utf-8")).hexdigest(),
            "sources": source_manifest,
        }

    manifest = GENERATED_DIR / "manifest.json"
    manifest.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return result


def ensure_frontend_assets() -> None:
    """Build only when generated entrypoints are absent (mainly local source runs)."""
    if all((GENERATED_DIR / name).is_file() for name in BUNDLES):
        return
    build_frontend_assets()


if __name__ == "__main__":
    build_frontend_assets()
